comments/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from landing import views

urlpatterns = [
    url(r'^landing/', views.landing, name='landing'),
]

mainMenu/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from mainMenu import views

urlpatterns = [
    url(r'^mainMenu/', views.index, name='index'),
    url(r'^tasks/$', views.tasks, name='tasks'),
    url(r'^tasks/(?P<task_id>\d+)/$', views.task, name='task'),
    url(r'^new_task/$', views.new_task, name='new_task'),
    url(r'^add_comment/$', views.add_comment, name='add_comment'),
    url(r'^edit_task/(?P<task_id>\d+)/$', views.edit_task, name='edit_task'),
]

task/urls.py
from django.contrib import admin
# from django.conf.urls import url, include
# from task import views
#
# urlpatterns = [
#     url(r'^landing/', views.landing, name='landing'),
# ]

taskTracker/urls.py
from django.urls import path
from django.contrib import admin
from django.conf.urls import url, include

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('mainMenu.urls', 'mainMenu'), namespace="mainMenu")),
]

users/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from landing import views

urlpatterns = [
    url(r'^landing/', views.landing, name='landing'),
]

youTrack/urls.py
from django.contrib import admin
from django.conf.urls import url, include

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('landing.urls')),
]

comments/models.py
from django.db import models


class Comment(models.Model):
    text = models.CharField(max_length=128)
    taskId = models.CharField(max_length=128)

    created = models.DateTimeField(auto_now_add=True,auto_now=False)

    def __str__(self):
        return self.text

landing/models.py
from django.db import models


class Task(models.Model):
    name = models.CharField(max_length=128)
    project = models.CharField(max_length=128)
    status = models.CharField(max_length=128)
    implementer = models.CharField(max_length=128)
    author = models.CharField(max_length=128)
    description = models.CharField(max_length=128)

    def __str__(self):
        return self.name

task/models.py
from django.db import models
from users.models import models, User


# class Status(models.Model):
#     name = models.CharField(max_length=24, blank=True, null=True, default=None)
#     is_active = models.BooleanField(default=True)
#     created = models.DateTimeField(auto_now_add=True, auto_now=False)
#     updated = models.DateTimeField(auto_now_add=False, auto_now=True)
#
#     def __str__(self):
#         return "Статус %s" % self.name
#
#     class Meta:
#         verbose_name = "Статус задачи"
#         verbose_name_plural = "Статусы задачи"


class Task(models.Model):
    name = models.CharField(max_length=128)
    project = models.CharField(max_length=128)
    status = models.CharField(max_length=128)
    implementer = models.CharField(max_length=128)
    author = models.CharField(max_length=128)
    description = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Comment(models.Model):
    task = models.ForeignKey(Task, on_delete='CASCADE')
    #user = models.ForeignKey(User, on_delete='CASCADE')
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'comments'

        def __str__(self):
            return self.text[:50] + "..."

users/models.py
from django.db import models


class User(models.Model):
    name = models.CharField(max_length=128)
    project = models.CharField(max_length=128)
    status = models.CharField(max_length=128)

    def __str__(self):
        return self.name

comments/forms.py
from django import forms
from .models import *


# class TaskForm(forms.ModelForm):
#     class Meta:
#         model = Task
#         exclude = [""]

task/forms.py
from django import forms
from .models import *


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = [""]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = [""]

users/forms.py
from django import forms
from .models import *


# class TaskForm(forms.ModelForm):
#     class Meta:
#         model = Task
#         exclude = [""]

comments/views.py
from django.shortcuts import render
from .forms import TaskForm


def landing(request):
    name = "Dmitryk"
    form = TaskForm(request.POST or None)

    if request.method == "POST":
        print(form)

        form_new = form.save()

    return render(request, 'landing/landing.html', locals())

mainMenu/views.py
from django.shortcuts import render
from task.models import Task
from task.forms import TaskForm
from task.forms import CommentForm
from django.http import HttpResponseRedirect
from django.urls import reverse


def index(request):
    return render(request, 'mainMenu/index.html', locals())


def tasks(request):
    """Выводит список задач."""
    tasks = Task.objects.order_by('name')
    context = {'tasks': tasks}
    return render(request, 'mainMenu/tasks.html', context)


def task(request, task_id):
    """Вьюха для одной задачи."""
    task = Task.objects.get(id=task_id)
    comments = task.comment_set.order_by('-date_added')
    context = {'task': task, 'comments': comments}
    return render(request, 'mainMenu/task.html', context)


def new_task(request):
    """Определяет новую задачу."""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = TaskForm()

    else:
        # Отправлены данные POST; обработать данные.
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mainMenu:tasks'))
    context = {'form': form}
    return render(request, 'mainMenu/new_task.html', context)


def edit_task(request, task_id):
    """Редактирует существующую запись."""
    task = Task.objects.get(id=task_id)

    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = TaskForm(instance=task)
    else:
        # Отправка данных POST; обработать данные.
        form = TaskForm(instance=task, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mainMenu:task',
                                                args=[task.id]))

    context = {'task': task, 'form': form}
    return render(request, 'mainMenu/edit_task.html', context)


def add_comment(request):
    """Добавляем комментарий"""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = CommentForm()

    else:
        # Отправлены данные POST; обработать данные.
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mainMenu:task',
                                                args=[task.id]))
    context = {'form': form}
    return render(request, 'mainMenu/add_comment.html', context)

task/views.py
from django.shortcuts import render
from .forms import TaskForm


def landing(request):
    name = "Dmitryk"
    form = TaskForm(request.POST or None)

    if request.method == "POST":
        print(form)

        form_new = form.save()

    return render(request, 'landing/landing.html', locals())

users/views.py
from django.shortcuts import render
from .forms import TaskForm


# def landing(request):
#     name = "Dmitryk"
#     form = TaskForm(request.POST or None)
#
#     if request.method == "POST":
#         print(form)
#
#         form_new = form.save()
#
#     return render(request, 'landing/landing.html', locals())

templates/landing/landing.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'style.css' %}">


    <style>
        html, body {
            height: 100%;
            max-height: 100%;
        }

        .top-container {
            padding-top: 10%;
        }

        .general_container{
            background-color: grey;
            height: 100%;
        }
    </style>

</head>
<body>

<div class="general_container">
    <div class="container top-container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <form action="" method="post" class="text-center">{% csrf_token %}
                    <div class="form-group">
                        <label>Название задачи</label>
                        <input type="text" name="{{ form.name.name }}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Проект</label>
                        <input type="text" name="{{ form.project.name }}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Статус</label>
                        <input type="text" name="{{ form.status.name }}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Исполнитель</label>
                        <input type="text" name="{{ form.implementer.name }}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Автор</label>
                        <input type="text" name="{{ form.author.name }}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Описание</label>
                        <input type="text" name="{{ form.description.name }}" class="form-control">
                    </div>

                    <div>
                        <button class="btn btn-primary" type="submit">Отправить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

</body>
</html>

templates/mainMenu/base.html
<p>
    <a href="{% url 'mainMenu:index' %}">TaskTracker</a>
    <a href="{% url 'mainMenu:tasks' %}">Tasks</a>
</p>
{% block content %}{% endblock content %}

templates/mainMenu/edit_task.html
{% extends "mainMenu/base.html" %}
{% block content %}
    <p><a href="{% url 'mainMenu:task' task.id %}">{{ task }}</a></p>

    <p>Edit task:</p>

    <form action="{% url 'mainMenu:edit_task' task.id %}" method='post'>
        {% csrf_token %}
        <div class="form-group">
            <label>Название задачи</label>
            <input type="text" name="{{ form.name.name }}" class="form-control">
        </div>
        <div class="form-group">
            <label>Проект</label>
            <input type="text" name="{{ form.project.name }}" class="form-control">
        </div>
        <div class="form-group">
            <label>Статус</label>
            <input type="text" name="{{ form.status.name }}" class="form-control">
        </div>
        <div class="form-group">
            <label>Исполнитель</label>
            <input type="text" name="{{ form.implementer.name }}" class="form-control">
        </div>
        <div class="form-group">
            <label>Автор</label>
            <input type="text" name="{{ form.author.name }}" class="form-control">
        </div>
        <div class="form-group">
            <label>Описание</label>
            <input type="text" name="{{ form.description.name }}" class="form-control">
        </div>
        <button name="submit">Сохранить изменения</button>
    </form>
{% endblock content %}

templates/mainMenu/index.html
{% extends "mainMenu/base.html" %}
{% block content %}
    <p>TaskTracker helps you keep track of your learning, for any topic you're
        learning about.</p>
{% endblock content %}

templates/mainMenu/new_task.html
{% extends "mainMenu/base.html" %}
{% block content %}
 <p>Add a new task:</p>
	 <form action="{% url 'mainMenu:new_task' %}" method='post'>
	 {% csrf_token %}
	                <div class="form-group">
                        <label>Название задачи</label>
                        <input type="text" name="{{ form.name.name }}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Проект</label>
                        <input type="text" name="{{ form.project.name }}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Статус</label>
                        <input type="text" name="{{ form.status.name }}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Исполнитель</label>
                        <input type="text" name="{{ form.implementer.name }}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Автор</label>
                        <input type="text" name="{{ form.author.name }}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Описание</label>
                        <input type="text" name="{{ form.description.name }}" class="form-control">
                    </div>
	 <button name="submit">Сохранить</button>
 </form>

{% endblock content %} 

templates/mainMenu/task.html
{% extends 'mainMenu/base.html' %}
{% block content %}
    <p> {{ task }}</p>

    <ul>

        <li>
            <p>Наименование: {{ task.name }}</p>
            <p>Проект: {{ task.project }}</p>
            <p>Автор: {{ task.author }}</p>
            <p>Исполнитель: {{ task.implementer }}</p>
            <p>Статус: {{ task.status }}</p>
            <p>Описание: {{ task.description }}</p>
        </li>

        <p>
            <a href="{% url 'mainMenu:edit_task' task.id %}">Редактировать запись</a>
        </p>


        <p>Комментарии к задаче</p>
        <p>
            <a href="{% url 'mainMenu:add_comment' %}">Добавить комментарий</a>
        </p>
        <ul>
            {% for comment in comments %}
                <li>
                    <p>{{ comment.text }}</p>
                </li>
            {% empty %}
                <li>Нет комментариев.</li>
            {% endfor %}
        </ul>


    </ul>
{% endblock content %}

templates/mainMenu/tasks.html
{% extends "mainMenu/base.html" %}
{% block content %}
    <p>Tasks</p>
    <ul>
        {% for task in tasks %}
            <li>
                <a href="{% url 'mainMenu:task' task.id %}">{{ task }}</a>
            </li>
        {% empty %}
            <li>No task have been added yet.</li>
        {% endfor %}
    </ul>

    <a href="{% url 'mainMenu:new_task' %}">Добавить задачу:</a>

{% endblock content %}